export const tradingPairs = {
    fx_majors: 'EURUSD, GBPUSD, AUDUSD, NZDUSD, USDCHF, USDCAD, USDJPY, EURGBP',
    fx_minors: 'AUDCAD, AUDCHF, AUDNZD, CADCHF, EURAUD, EURCAD, EURCHF, EURNZD, GBPAUD, GBPCAD, GBPCHF, GBPNZD, NZDCAD, NZDCHF, USDCNH, USDNOK, USDHKD, USDSGD, USDTRY, USDZAR',
    fx_yen: 'EURJPY, CADJPY, GBPJPY, NZDJPY, CHFJPY, NOKJPY, AUDJPY',
    spot_silver: 'XAGUSD',
    spot_gold: 'XAUUSD, XAUEUR',
    spot_energy: 'UKOIL, CRUDEOIL',
    dow: 'WS30',
    spot_indices: 'HSI, UK100, NDX, AUS200, FCHI, GDAXI, STOXX50E, RUSS2000, ESP35, CHINA50, J225',
    spxm: 'SPXm',
    crypto: 'BTCUSD, LTCUSD, ETHUSD'
};